spring:
  datasource:
    url: jdbc:postgresql://10.0.14.136:5432/${DB_NAME:biddo}?reWriteBatchedInserts=true

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

  data:
    redis:
      sentinel:
        master: biddo-master
        nodes: 10.0.14.136:26379,10.0.14.136:26380,10.0.14.136:26381

  elasticsearch:
    uris: http://10.0.14.136:9200

  kafka:
    bootstrap-servers: 10.0.14.136:9092

management:
  otlp:
    tracing:
      endpoint: http://10.0.14.136:4318/v1/traces