spring:
  application:
    name: biddo

  datasource:
    url: jdbc:postgresql://localhost:5432/biddo
    username: ${DB_USERNAME:biddo}
    password: ${DB_PASSWORD:biddo}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 9090

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBiaWRkbyBqd3QgdG9rZW4gZ2VuZXJhdGlvbg==}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000